// Mock sellers database for products
export interface Seller {
  id: number;
  name: string;
  avatar: string;
  email: string;
  phone: string;
  location: string;
  joinYear: number;
  rating: number;
  ratingCount: number;
  productIds: number[];
  about?: string;
}

export const sellers: Seller[] = [
  {
    id: 1,
    name: "Nguyễn Văn An",
    avatar: "/images.jpeg",
    email: "an.nguyen@gmail.com",
    phone: "0987 111 222",
    location: "Hà Nội",
    joinYear: 2021,
    rating: 4.7,
    ratingCount: 18,
    productIds: [0, 8, 16, 24, 32, 50, 60],
    about: "Chuyên cung cấp các sản phẩm công nghệ mới nhất với giá cả cạnh tranh và dịch vụ tận tâm.",
  },
  {
    id: 2,
    name: "Trần Thị Bình",
    avatar: "/about.png",
    email: "binh.tran@gmail.com",
    phone: "0912 222 333",
    location: "Hồ Chí Minh",
    joinYear: 2020,
    rating: 4.8,
    ratingCount: 25,
    // productIds: [1, 9, 17, 25, 33, 51, 61],
    productIds: [25, 51, 61],
    about: "Đam mê công nghệ, luôn mang đến cho khách hàng những sản phẩm chất lượng và uy tín.",
  },
  {
    id: 3,
    name: "Lê Văn Cường",
    avatar: "/hero.png",
    email: "cuong.le@gmail.com",
    phone: "0901 333 444",
    location: "Đà Nẵng",
    joinYear: 2022,
    rating: 4.6,
    ratingCount: 14,
    productIds: [2, 10, 18, 26, 34, 52, 62],
    about: "Luôn cập nhật các sản phẩm mới, hỗ trợ khách hàng tận tình 24/7.",
  },
  {
    id: 4,
    name: "Phạm Thị Dung",
    avatar: "/logo-light@3x.webp",
    email: "dung.pham@gmail.com",
    phone: "0934 444 555",
    location: "Cần Thơ",
    joinYear: 2023,
    rating: 4.9,
    ratingCount: 30,
    productIds: [3, 11, 19, 27, 35, 63],
    about: "Kinh nghiệm nhiều năm trong lĩnh vực điện tử, cam kết sản phẩm chính hãng.",
  },
  {
    id: 5,
    name: "Hoàng Văn Em",
    avatar: "/vercel.svg",
    email: "em.hoang@gmail.com",
    phone: "0978 555 666",
    location: "Hải Phòng",
    joinYear: 2021,
    rating: 4.5,
    ratingCount: 12,
    productIds: [4, 20, 28, 64],
    about: "Dịch vụ nhanh chóng, sản phẩm đa dạng, luôn đặt lợi ích khách hàng lên hàng đầu.",
  },
  {
    id: 6,
    name: "Vũ Thị Phương",
    avatar: "/next.svg",
    email: "phuong.vu@gmail.com",
    phone: "0967 666 777",
    location: "Huế",
    joinYear: 2020,
    rating: 4.4,
    ratingCount: 10,
    productIds: [5, 21, 29],
    about: "Chuyên cung cấp các sản phẩm điện tử, hỗ trợ khách hàng tận tâm.",
  },
  {
    id: 7,
    name: "Đặng Văn Quang",
    avatar: "/file.svg",
    email: "quang.dang@gmail.com",
    phone: "0956 777 888",
    location: "Bình Dương",
    joinYear: 2022,
    rating: 4.7,
    ratingCount: 16,
    productIds: [6, 22, 30],
    about: "Luôn mang đến sản phẩm chất lượng, giá tốt và dịch vụ hậu mãi chu đáo.",
  },
  {
    id: 8,
    name: "Bùi Thị Hạnh",
    avatar: "/window.svg",
    email: "hanh.bui@gmail.com",
    phone: "0945 888 999",
    location: "Nha Trang",
    joinYear: 2021,
    rating: 4.6,
    ratingCount: 13,
    productIds: [7, 15, 31],
    about: "Khách hàng là ưu tiên số một, luôn hỗ trợ tận tình và chu đáo.",
  },
  {
    id: 9,
    name: "Watch Center",
    avatar: "/images.jpeg",
    email: "watchcenter@gmail.com",
    phone: "0933 999 000",
    location: "Vũng Tàu",
    joinYear: 2020,
    rating: 4.8,
    ratingCount: 20,
    productIds: [8],
  },
  {
    id: 10,
    name: "TV World",
    avatar: "/about.png",
    email: "tvworld@gmail.com",
    phone: "0922 000 111",
    location: "Quảng Ninh",
    joinYear: 2023,
    rating: 4.7,
    ratingCount: 17,
    productIds: [9],
  },
  {
    id: 11,
    name: "Game Center",
    avatar: "/hero.png",
    email: "gamecenter@gmail.com",
    phone: "0911 111 222",
    location: "Thái Nguyên",
    joinYear: 2021,
    rating: 4.5,
    ratingCount: 11,
    productIds: [10,29],
  },
  {
    id: 12,
    name: "Photo Pro",
    avatar: "/logo-light@3x.webp",
    email: "photopro@gmail.com",
    phone: "0900 222 333",
    location: "Lâm Đồng",
    joinYear: 2022,
    rating: 4.9,
    ratingCount: 28,
    productIds: [11, 302],
    about: "Chuyên nghiệp về nhiếp ảnh, cung cấp thiết bị và dịch vụ nhiếp ảnh chất lượng.",
  },
  {
    id: 13,
    name: "Mobile Pro",
    avatar: "/images.jpeg",
    email: "mobilepro@gmail.com",
    phone: "0988 123 456",
    location: "Hà Nội",
    joinYear: 2022,
    rating: 4.7,
    ratingCount: 19,
    productIds: [],
  },
  {
    id: 14,
    name: "Apple Store",
    avatar: "/about.png",
    email: "applestore@gmail.com",
    phone: "0913 234 567",
    location: "Hồ Chí Minh",
    joinYear: 2021,
    rating: 4.8,
    ratingCount: 22,
    productIds: [72],
    about: "Đại lý chính thức Apple, cung cấp sản phẩm chính hãng.",
  },
  {
    id: 15,
    name: "Samsung Center",
    avatar: "/hero.png",
    email: "samsungcenter@gmail.com",
    phone: "0902 345 678",
    location: "Đà Nẵng",
    joinYear: 2023,
    rating: 4.7,
    ratingCount: 15,
    productIds: [],
    about: "Chuyên cung cấp các sản phẩm Samsung chính hãng với dịch vụ bảo hành toàn quốc.",
  },
  {
    id: 16,
    name: "Tablet World",
    avatar: "/logo-light@3x.webp",
    email: "tabletworld@gmail.com",
    phone: "0935 456 789",
    location: "Cần Thơ",
    joinYear: 2020,
    rating: 4.7,
    ratingCount: 17,
    productIds: [15],
  },
  {
    id: 17,
    name: "Audio Center",
    avatar: "/vercel.svg",
    email: "audiocenter@gmail.com",
    phone: "0979 567 890",
    location: "Hải Phòng",
    joinYear: 2022,
    rating: 4.5,
    ratingCount: 13,
    productIds: [16],
  },
  {
    id: 18,
    name: "Game Pro",
    avatar: "/next.svg",
    email: "gamepro@gmail.com",
    phone: "0968 678 901",
    location: "Huế",
    joinYear: 2021,
    rating: 4.4,
    ratingCount: 11,
    productIds: [17],
  },
  {
    id: 19,
    name: "Drone World",
    avatar: "/file.svg",
    email: "droneworld@gmail.com",
    phone: "0957 789 012",
    location: "Bình Dương",
    joinYear: 2023,
    rating: 4.7,
    ratingCount: 16,
    productIds: [18],
  },
  {
    id: 20,
    name: "Camera Pro",
    avatar: "/window.svg",
    email: "camerapro@gmail.com",
    phone: "0946 890 123",
    location: "Nha Trang",
    joinYear: 2020,
    rating: 4.6,
    ratingCount: 14,
    productIds: [19],
  },
  {
    id: 21,
    name: "Sport Watch",
    avatar: "/images.jpeg",
    email: "sportwatch@gmail.com",
    phone: "0934 901 234",
    location: "Vũng Tàu",
    joinYear: 2022,
    rating: 4.8,
    ratingCount: 18,
    productIds: [20],
  },
  {
    id: 22,
    name: "TV Pro",
    avatar: "/about.png",
    email: "tvpro@gmail.com",
    phone: "0923 012 345",
    location: "Quảng Ninh",
    joinYear: 2021,
    rating: 4.7,
    ratingCount: 15,
    productIds: [21],
  },
  {
    id: 23,
    name: "Gaming Store",
    avatar: "/hero.png",
    email: "gamingstore@gmail.com",
    phone: "0912 123 456",
    location: "Thái Nguyên",
    joinYear: 2023,
    rating: 4.5,
    ratingCount: 12,
    productIds: [22],
  },
  {
    id: 24,
    name: "Photo World",
    avatar: "/logo-light@3x.webp",
    email: "photoworld@gmail.com",
    phone: "0901 234 567",
    location: "Lâm Đồng",
    joinYear: 2020,
    rating: 4.9,
    ratingCount: 20,
    productIds: [],
  },
  {
    id: 99,
    name: "Demo User",
    avatar: "/about.png",
    email: "demo@email.com",
    phone: "0123456789",
    location: "Hà Nội",
    joinYear: 2025,
    rating: 5,
    ratingCount: 23,
    productIds: [1, 9, 12, 13, 14, 37, 38, 39],
    about: "Demo user for testing.",
  },
  {
    id: 100,
    name: "TechStore Pro",
    avatar: "/images.jpeg",
    email: "techstorepro@gmail.com",
    phone: "0903 456 789",
    location: "Hà Nội",
    joinYear: 2022,
    rating: 4.8,
    ratingCount: 32,
    productIds: [101],
    about: "Cửa hàng công nghệ uy tín chuyên cung cấp các sản phẩm điện tử chất lượng cao.",
  },
  {
    id: 101,
    name: "Apple Center",
    avatar: "/about.png",
    email: "applecenter@gmail.com",
    phone: "0904 567 890",
    location: "TP.HCM",
    joinYear: 2021,
    rating: 4.9,
    ratingCount: 45,
    productIds: [102],
    about: "Đại lý chính thức Apple tại Việt Nam, cung cấp sản phẩm chính hãng với bảo hành toàn cầu.",
  },
  {
    id: 102,
    name: "Samsung Store",
    avatar: "/hero.png",
    email: "samsungstore@gmail.com",
    phone: "0905 678 901",
    location: "Đà Nẵng",
    joinYear: 2022,
    rating: 4.7,
    ratingCount: 28,
    productIds: [103, 73],
    about: "Cửa hàng Samsung chính hãng tại Đà Nẵng, bảo hành 24 tháng toàn quốc.",
  },
  {
    id: 103,
    name: "Digital World",
    avatar: "/logo-light@3x.webp",
    email: "digitalworld@gmail.com",
    phone: "0906 789 012",
    location: "Hà Nội",
    joinYear: 2023,
    rating: 4.6,
    ratingCount: 19,
    productIds: [104],
    about: "Thế giới số - nơi mua sắm công nghệ đáng tin cậy với giá cả cạnh tranh.",
  },
  {
    id: 104,
    name: "GameStore",
    avatar: "/images.jpeg",
    email: "gamestore@gmail.com",
    phone: "0907 890 123",
    location: "Hà Nội",
    joinYear: 2021,
    rating: 4.5,
    ratingCount: 23,
    productIds: [201],
    about: "Cửa hàng game chuyên nghiệp, cung cấp các sản phẩm gaming chính hãng.",
  },
  {
    id: 105,
    name: "Drone Pro",
    avatar: "/about.png",
    email: "dronepro@gmail.com",
    phone: "0908 901 234",
    location: "TP.HCM",
    joinYear: 2022,
    rating: 4.8,
    ratingCount: 36,
    productIds: [202],
    about: "Chuyên gia về drone và thiết bị bay không người lái, dịch vụ hậu mãi chu đáo.",
  },
  {
    id: 106,
    name: "Camera World",
    avatar: "/hero.png",
    email: "cameraworld@gmail.com",
    phone: "0909 012 345",
    location: "Đà Nẵng",
    joinYear: 2021,
    rating: 4.7,
    ratingCount: 31,
    productIds: [203],
    about: "Thế giới máy ảnh - nơi mua sắm thiết bị nhiếp ảnh chuyên nghiệp.",
  },
  {
    id: 107,
    name: "GameCenter",
    avatar: "/logo-light@3x.webp",
    email: "gamecenter@gmail.com",
    phone: "0910 123 456",
    location: "Hà Nội",
    joinYear: 2022,
    rating: 4.6,
    ratingCount: 25,
    productIds: [301],
    about: "Trung tâm game hàng đầu, cung cấp các sản phẩm gaming chất lượng cao.",
  },
  {
    id: 109,
    name: "Sport Gear",
    avatar: "/about.png",
    email: "sportgear@gmail.com",
    phone: "0912 345 678",
    location: "Hà Nội",
    joinYear: 2022,
    rating: 4.7,
    ratingCount: 29,
    productIds: [303],
    about: "Thiết bị thể thao chuyên nghiệp, cung cấp các sản phẩm theo dõi sức khỏe.",
  },
  {
    id: 110,
    name: "TV Store",
    avatar: "/hero.png",
    email: "tvstore@gmail.com",
    phone: "0913 456 789",
    location: "TP.HCM",
    joinYear: 2023,
    rating: 4.8,
    ratingCount: 38,
    productIds: [304],
    about: "Cửa hàng TV chuyên nghiệp, cung cấp các sản phẩm TV cao cấp với dịch vụ lắp đặt.",
  },
  {
    id: 111,
    name: "Gaming Pro",
    avatar: "/logo-light@3x.webp",
    email: "gamingpro@gmail.com",
    phone: "0914 567 890",
    location: "Hà Nội",
    joinYear: 2022,
    rating: 4.6,
    ratingCount: 27,
    productIds: [305],
    about: "Chuyên gia gaming, cung cấp các thiết bị và phụ kiện gaming chất lượng cao.",
  },
  {
    id: 117,
    name: "Audio Store",
    avatar: "/next.svg",
    email: "audiostore@gmail.com",
    phone: "0967 666 777",
    location: "Hà Nội",
    joinYear: 2020,
    rating: 4.4,
    ratingCount: 10,
    productIds: [70],
    about: "Chuyên cung cấp các sản phẩm âm thanh chất lượng cao.",
  },
  {
    id: 118,
    name: "Audio Pro",
    avatar: "/file.svg",
    email: "audiopro@gmail.com",
    phone: "0956 777 888",
    location: "TP.HCM",
    joinYear: 2022,
    rating: 4.7,
    ratingCount: 16,
    productIds: [71],
    about: "Chuyên gia âm thanh, cung cấp thiết bị audio chuyên nghiệp.",
  },
  {
    id: 121,
    name: "JBL Store",
    avatar: "/about.png",
    email: "jblstore@gmail.com",
    phone: "0922 000 111",
    location: "Hà Nội",
    joinYear: 2023,
    rating: 4.7,
    ratingCount: 17,
    productIds: [74],
    about: "Chuyên cung cấp các sản phẩm JBL chính hãng.",
  },
  {
    id: 122,
    name: "UE Store",
    avatar: "/hero.png",
    email: "uestore@gmail.com",
    phone: "0911 111 222",
    location: "TP.HCM",
    joinYear: 2021,
    rating: 4.5,
    ratingCount: 11,
    productIds: [75],
    about: "Ultimate Ears - chuyên gia loa bluetooth.",
  },
  {
    id: 123,
    name: "Bose Store",
    avatar: "/logo-light@3x.webp",
    email: "bosestore@gmail.com",
    phone: "0900 222 333",
    location: "Hà Nội",
    joinYear: 2022,
    rating: 4.9,
    ratingCount: 28,
    productIds: [76],
    about: "Cửa hàng Bose chính hãng, âm thanh chất lượng cao.",
  },
  {
    id: 124,
    name: "Marshall Store",
    avatar: "/images.jpeg",
    email: "marshallstore@gmail.com",
    phone: "0988 123 456",
    location: "Đà Nẵng",
    joinYear: 2022,
    rating: 4.7,
    ratingCount: 19,
    productIds: [77],
    about: "Marshall - âm thanh rock n' roll chính hãng.",
  },
  {
    id: 125,
    name: "Harman Store",
    avatar: "/about.png",
    email: "harmanstore@gmail.com",
    phone: "0913 234 567",
    location: "Hà Nội",
    joinYear: 2021,
    rating: 4.8,
    ratingCount: 22,
    productIds: [78],
    about: "Harman Kardon - âm thanh cao cấp chính hãng.",
  },
  {
    id: 126,
    name: "Drone Store",
    avatar: "/hero.png",
    email: "dronestore@gmail.com",
    phone: "0902 345 678",
    location: "TP.HCM",
    joinYear: 2023,
    rating: 4.7,
    ratingCount: 15,
    productIds: [30],
    about: "Chuyên cung cấp drone và thiết bị bay không người lái.",
  },
  {
    id: 127,
    name: "GoPro Store",
    avatar: "/logo-light@3x.webp",
    email: "goprostore@gmail.com",
    phone: "0935 456 789",
    location: "Hà Nội",
    joinYear: 2020,
    rating: 4.7,
    ratingCount: 17,
    productIds: [31],
    about: "Đại lý chính thức GoPro, camera hành động chính hãng.",
  },
  {
    id: 128,
    name: "Canon Store",
    avatar: "/vercel.svg",
    email: "canonstore@gmail.com",
    phone: "0979 567 890",
    location: "Đà Nẵng",
    joinYear: 2022,
    rating: 4.5,
    ratingCount: 13,
    productIds: [32],
    about: "Cửa hàng Canon chính hãng, máy ảnh chuyên nghiệp.",
  },
  {
    id: 129,
    name: "Sony Store",
    avatar: "/next.svg",
    email: "sonystore@gmail.com",
    phone: "0968 678 901",
    location: "Hà Nội",
    joinYear: 2021,
    rating: 4.4,
    ratingCount: 11,
    productIds: [33],
    about: "Sony - công nghệ hình ảnh hàng đầu.",
  },
  {
    id: 130,
    name: "Fujifilm Store",
    avatar: "/file.svg",
    email: "fujifilmstore@gmail.com",
    phone: "0957 789 012",
    location: "TP.HCM",
    joinYear: 2023,
    rating: 4.7,
    ratingCount: 16,
    productIds: [34],
    about: "Fujifilm - màu sắc tự nhiên, chất lượng cao.",
  },
  {
    id: 131,
    name: "Nikon Store",
    avatar: "/window.svg",
    email: "nikonstore@gmail.com",
    phone: "0946 890 123",
    location: "Hà Nội",
    joinYear: 2020,
    rating: 4.6,
    ratingCount: 14,
    productIds: [35],
    about: "Nikon - độ tin cậy và chất lượng hình ảnh.",
  },
  {
    id: 132,
    name: "Panasonic Store",
    avatar: "/images.jpeg",
    email: "panasonicstore@gmail.com",
    phone: "0934 901 234",
    location: "Đà Nẵng",
    joinYear: 2022,
    rating: 4.8,
    ratingCount: 18,
    productIds: [36],
    about: "Panasonic - công nghệ Lumix chuyên nghiệp.",
  }
]; 