import { STATUS_AUCTIONS } from "@/constants/app.enum";

// Simplified unified product interface - only includes fields supported by existing API routes
export interface UnifiedProduct {
  id: number | string;
  name: string;
  image: string[];
  description?: string;
  startingPrice: string;
  buyNow?: string;
  currentPrice?: string;
  finalPrice?: string;
  timeLeft?: string;
  endTime?: string;
  seller: string;
  sellerId: number;
  location?: string;
  category?: string;
  condition?: "new" | "used" | "refurbished";
  status: STATUS_AUCTIONS;
  type: STATUS_AUCTIONS;
  views?: number;
  createdAt?: string;
  updatedAt?: string;
  isWatched?: boolean;
  owner?: {
    _id?: string | number;
    full_name?: string;
  };
}

// Simplified product array - removed bid tracking and unsupported functionality
export const unifiedProducts: UnifiedProduct[] = [
  // Product 0 - Demo User is watching (SOON product)
  {
    id: 0,
    name: "iPhone 15 Pro Max 512GB",
    image: ["/images.jpeg", "/ava-dark.png", "/ava-light.png"],
    description:
      "iPhone 15 Pro Max 512GB mới nhất từ Apple với chip A17 Pro, camera 48MP, màn hình 6.7 inch Super Retina XDR OLED.",
    startingPrice: "28.000.000đ",
    buyNow: "32.000.000đ",
    currentPrice: "28.000.000đ",
    seller: "TechStore Pro",
    sellerId: 100,
    location: "Hà Nội",
    category: "Smartphone",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 45,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  // Products from productsMock.ts - Now (auctioning) products
  {
    id: 1,
    name: "iPhone 15 Pro Max 256GB",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "iPhone 15 Pro Max 256GB mới nhất từ Apple với chip A17 Pro, camera 48MP, màn hình 6.7 inch Super Retina XDR OLED.",
    startingPrice: "25.000.000đ",
    buyNow: "28.000.000đ",
    currentPrice: "25.000.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Smartphone",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 45,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 101,
    name: "iPhone 15 Pro Max 256GB",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "iPhone 15 Pro Max 256GB từ TechStore Pro - sản phẩm chính hãng, bảo hành 12 tháng.",
    startingPrice: "25.000.000đ",
    buyNow: "28.000.000đ",
    currentPrice: "25.000.000đ",
    seller: "TechStore Pro",
    sellerId: 100,
    location: "Hà Nội",
    category: "Smartphone",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 67,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 2,
    name: "MacBook Air M2 13 inch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "MacBook Air M2 13 inch với chip M2 mạnh mẽ, màn hình Retina, pin trâu 18 giờ.",
    startingPrice: "22.000.000đ",
    buyNow: "25.000.000đ",
    currentPrice: "22.000.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Laptop",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 38,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 102,
    name: "MacBook Air M2 13 inch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "MacBook Air M2 13 inch từ Apple Center - chính hãng Apple, bảo hành toàn cầu.",
    startingPrice: "22.000.000đ",
    buyNow: "25.000.000đ",
    currentPrice: "22.000.000đ",
    seller: "Apple Center",
    sellerId: 101,
    location: "TP.HCM",
    category: "Laptop",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 52,
    createdAt: "2024-01-17",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 3,
    name: "Samsung Galaxy S24 Ultra",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Samsung Galaxy S24 Ultra với S Pen tích hợp, camera 200MP, màn hình 6.8 inch Dynamic AMOLED 2X.",
    startingPrice: "18.500.000đ",
    buyNow: "21.000.000đ",
    currentPrice: "18.500.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Smartphone",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 41,
    createdAt: "2024-01-14",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 103,
    name: "Samsung Galaxy S24 Ultra",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Samsung Galaxy S24 Ultra từ Samsung Store - chính hãng Samsung, bảo hành 24 tháng.",
    startingPrice: "18.500.000đ",
    buyNow: "21.000.000đ",
    currentPrice: "18.500.000đ",
    seller: "Samsung Store",
    sellerId: 102,
    location: "Đà Nẵng",
    category: "Smartphone",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 58,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 4,
    name: "iPad Pro 12.9 inch M2",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "iPad Pro 12.9 inch M2 với chip M2, màn hình Liquid Retina XDR, hỗ trợ Apple Pencil 2.",
    startingPrice: "28.000.000đ",
    buyNow: "32.000.000đ",
    currentPrice: "28.000.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Tablet",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 33,
    createdAt: "2024-01-13",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 104,
    name: "iPad Pro 12.9 inch M2",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "iPad Pro 12.9 inch M2 từ Digital World - chính hãng Apple, bảo hành 12 tháng.",
    startingPrice: "28.000.000đ",
    buyNow: "32.000.000đ",
    currentPrice: "28.000.000đ",
    seller: "Digital World",
    sellerId: 103,
    location: "Hà Nội",
    category: "Tablet",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 44,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 5,
    name: "Sony WH-1000XM5",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Sony WH-1000XM5 - tai nghe chống ồn hàng đầu thế giới với công nghệ LDAC.",
    startingPrice: "6.500.000đ",
    buyNow: "7.200.000đ",
    currentPrice: "6.500.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Audio",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 29,
    createdAt: "2024-01-12",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 105,
    name: "Sony WH-1000XM5",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Sony WH-1000XM5 từ AudioPro - hàng chính hãng, bảo hành 24 tháng.",
    startingPrice: "6.500.000đ",
    buyNow: "7.200.000đ",
    currentPrice: "6.500.000đ",
    seller: "AudioPro",
    sellerId: 104,
    location: "Hà Nội",
    category: "Audio",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 35,
    createdAt: "2024-01-14",
    updatedAt: "2024-01-20",
    isWatched: false,
  },

  // Products from productsMock.ts - Done products
  {
    id: 6,
    name: "Nintendo Switch OLED",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Nintendo Switch OLED với màn hình 7 inch OLED, pin trâu 4.5-9 giờ chơi game.",
    startingPrice: "8.200.000đ",
    finalPrice: "9.500.000đ",
    endTime: "2 giờ trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 89,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 201,
    name: "Nintendo Switch OLED",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Nintendo Switch OLED từ GameStore - chính hãng Nintendo, bảo hành 12 tháng.",
    startingPrice: "8.200.000đ",
    finalPrice: "9.500.000đ",
    endTime: "2 giờ trước",
    seller: "GameStore",
    sellerId: 104,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 112,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 7,
    name: "DJI Mini 3 Pro Drone",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "DJI Mini 3 Pro Drone - drone nhỏ gọn với camera 4K, thời gian bay 34 phút.",
    startingPrice: "12.800.000đ",
    finalPrice: "14.200.000đ",
    endTime: "5 giờ trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Drone",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 76,
    createdAt: "2024-01-09",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 202,
    name: "DJI Mini 3 Pro Drone",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "DJI Mini 3 Pro Drone từ Drone Pro - chính hãng DJI, bảo hành 12 tháng.",
    startingPrice: "12.800.000đ",
    finalPrice: "14.200.000đ",
    endTime: "5 giờ trước",
    seller: "Drone Pro",
    sellerId: 105,
    location: "TP.HCM",
    category: "Drone",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 93,
    createdAt: "2024-01-07",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 8,
    name: "GoPro Hero 11 Black",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "GoPro Hero 11 Black - camera hành động 5.3K với HyperSmooth 5.0.",
    startingPrice: "9.500.000đ",
    finalPrice: "10.800.000đ",
    endTime: "1 ngày trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Camera",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 62,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 203,
    name: "GoPro Hero 11 Black",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "GoPro Hero 11 Black từ Camera World - chính hãng GoPro, bảo hành 12 tháng.",
    startingPrice: "9.500.000đ",
    finalPrice: "10.800.000đ",
    endTime: "1 ngày trước",
    seller: "Camera World",
    sellerId: 106,
    location: "Đà Nẵng",
    category: "Camera",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 78,
    createdAt: "2024-01-06",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 9,
    name: "Apple Watch Series 9",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Apple Watch Series 9 với chip S9, màn hình Always-On Retina, theo dõi sức khỏe nâng cao.",
    startingPrice: "11.200.000đ",
    finalPrice: "12.500.000đ",
    endTime: "3 ngày trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Smartwatch",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 51,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 10,
    name: "Samsung QLED 4K TV 65 inch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Samsung QLED 4K TV 65 inch với công nghệ Quantum Dot, HDR10+, Smart TV.",
    startingPrice: "25.000.000đ",
    finalPrice: "28.000.000đ",
    endTime: "1 tuần trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "TV",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 43,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-20",
    isWatched: false,
  },

  // Products from productsMock.ts - Soon (upcoming) products
  {
    id: 11,
    name: "PlayStation 5 Digital Edition",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "PlayStation 5 Digital Edition với SSD 825GB, ray tracing, 4K gaming.",
    startingPrice: "10.500.000đ",
    buyNow: "11.800.000đ",
    timeLeft: "2 ngày",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 23,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 301,
    name: "PlayStation 5 Digital Edition",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "PlayStation 5 Digital Edition từ GameCenter - chính hãng Sony, bảo hành 12 tháng.",
    startingPrice: "10.500.000đ",
    buyNow: "11.800.000đ",
    timeLeft: "2 ngày",
    seller: "GameCenter",
    sellerId: 107,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 31,
    createdAt: "2024-01-19",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 12,
    name: "Canon EOS R6 Mark II",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Canon EOS R6 Mark II - mirrorless camera 24.2MP với Dual Pixel CMOS AF II.",
    startingPrice: "35.000.000đ",
    buyNow: "38.500.000đ",
    timeLeft: "3 ngày",
    seller: "Photo Pro",
    sellerId: 12,
    location: "TP.HCM",
    category: "Camera",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 27,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 302,
    name: "Canon EOS R6 Mark II",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Canon EOS R6 Mark II từ Photo Pro - chính hãng Canon, bảo hành 24 tháng.",
    startingPrice: "35.000.000đ",
    buyNow: "38.500.000đ",
    timeLeft: "3 ngày",
    seller: "Photo Pro",
    sellerId: 12,
    location: "TP.HCM",
    category: "Camera",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 27,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 13,
    name: "Garmin Fenix 7 Watch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Garmin Fenix 7 Watch - smartwatch thể thao với GPS, theo dõi sức khỏe toàn diện.",
    startingPrice: "16.500.000đ",
    buyNow: "19.000.000đ",
    timeLeft: "5 ngày",
    seller: "Sport Gear",
    sellerId: 109,
    location: "Hà Nội",
    category: "Smartwatch",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 15,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 303,
    name: "Garmin Fenix 7 Watch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Garmin Fenix 7 Watch từ Sport Gear - chính hãng Garmin, bảo hành 12 tháng.",
    startingPrice: "16.500.000đ",
    buyNow: "19.000.000đ",
    timeLeft: "5 ngày",
    seller: "Sport Gear",
    sellerId: 109,
    location: "Hà Nội",
    category: "Smartwatch",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 22,
    createdAt: "2024-01-17",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 14,
    name: "LG OLED 4K TV 77 inch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description: "LG OLED 4K TV 77 inch với công nghệ OLED, AI ThinQ, webOS.",
    startingPrice: "45.000.000đ",
    buyNow: "50.000.000đ",
    timeLeft: "1 tuần",
    seller: "TV Store",
    sellerId: 110,
    location: "TP.HCM",
    category: "TV",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 12,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 304,
    name: "LG OLED 4K TV 77 inch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "LG OLED 4K TV 77 inch từ TV Store - chính hãng LG, bảo hành 24 tháng.",
    startingPrice: "45.000.000đ",
    buyNow: "50.000.000đ",
    timeLeft: "1 tuần",
    seller: "TV Store",
    sellerId: 110,
    location: "TP.HCM",
    category: "TV",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 18,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 15,
    name: "Steam Deck 512GB",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Steam Deck 512GB - handheld gaming PC với màn hình 7 inch, SSD 512GB.",
    startingPrice: "14.500.000đ",
    buyNow: "17.000.000đ",
    timeLeft: "10 ngày",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 8,
    createdAt: "2024-01-14",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 305,
    name: "Steam Deck 512GB",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description:
      "Steam Deck 512GB từ Gaming Pro - chính hãng Valve, bảo hành 12 tháng.",
    startingPrice: "14.500.000đ",
    buyNow: "17.000.000đ",
    timeLeft: "10 ngày",
    seller: "Gaming Pro",
    sellerId: 111,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.INITIAL,
    type: STATUS_AUCTIONS.INITIAL,
    views: 14,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    isWatched: false,
  },

  // Products from profileMock.ts - Demo User's seller products
  {
    id: 16,
    name: "Demo Product",
    image: ["/about.png", "/about.png", "/about.png"],
    description: "Demo Product - sản phẩm mẫu từ Demo User",
    startingPrice: "1.000.000đ",
    buyNow: "2.000.000đ",
    timeLeft: "1 ngày",
    currentPrice: "2.000.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Electronics",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 25,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 40,
    name: "Demo Laptop Pro",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description: "Demo Laptop Pro - laptop mẫu từ Demo User",
    startingPrice: "25.000.000đ",
    buyNow: "30.000.000đ",
    timeLeft: "3 giờ",
    currentPrice: "27.200.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Laptop",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 42,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 41,
    name: "Demo Smartphone X",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description: "Demo Smartphone X - smartphone mẫu từ Demo User",
    startingPrice: "12.000.000đ",
    buyNow: "15.000.000đ",
    timeLeft: "2 giờ 30 phút",
    currentPrice: "13.800.000đ",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Smartphone",
    condition: "new",
    status: STATUS_AUCTIONS.HAPPENING,
    type: STATUS_AUCTIONS.HAPPENING,
    views: 38,
    createdAt: "2024-01-17",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 37,
    name: "Demo Camera Pro",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description: "Demo Camera Pro - camera mẫu từ Demo User",
    startingPrice: "35.000.000đ",
    finalPrice: "38.500.000đ",
    endTime: "1 ngày trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Camera",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 67,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 38,
    name: "Demo Gaming Console",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description: "Demo Gaming Console - console mẫu từ Demo User",
    startingPrice: "15.000.000đ",
    finalPrice: "17.200.000đ",
    endTime: "2 ngày trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Gaming",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 54,
    createdAt: "2024-01-09",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
  {
    id: 39,
    name: "Demo Smart Watch",
    image: ["/images.jpeg", "/images.jpeg", "/images.jpeg"],
    description: "Demo Smart Watch - smartwatch mẫu từ Demo User",
    startingPrice: "8.500.000đ",
    finalPrice: "9.800.000đ",
    endTime: "3 ngày trước",
    seller: "Demo User",
    sellerId: 99,
    location: "Hà Nội",
    category: "Smartwatch",
    condition: "new",
    status: STATUS_AUCTIONS.ENDED,
    type: STATUS_AUCTIONS.ENDED,
    views: 41,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-20",
    isWatched: false,
  },
];

// Helper functions that work with existing API routes
export function getProductsBySeller(sellerId: number) {
  return unifiedProducts.filter((p) => p.sellerId === sellerId);
}

export function getSellerProductsByStatus(
  sellerId: number,
  status: STATUS_AUCTIONS
) {
  return unifiedProducts.filter(
    (p) => p.sellerId === sellerId && p.status === status
  );
}

// Helper: Get products for the landing/features page
export function getFeatureProducts() {
  return unifiedProducts.filter(
    (p) => p.status === STATUS_AUCTIONS.HAPPENING || p.status === STATUS_AUCTIONS.INITIAL
  );
}

// Helper: Get products by status (for AUCTION_BY_STATUS route)
export function getProductsByStatus(status: STATUS_AUCTIONS) {
  return unifiedProducts.filter((p) => p.status === status);
}

// Helper: Get products by category (for AUCTION_BY_CATEGORY route)
export function getProductsByCategory(category: string) {
  return unifiedProducts.filter((p) => p.category === category);
}

// Helper: Search products by name (for AUCTION_SEARCH route)
export function searchProducts(keyword: string) {
  return unifiedProducts.filter((p) =>
    p.name.toLowerCase().includes(keyword.toLowerCase())
  );
}

// Helper: Get product by ID (for AUCTION_BY_ID route)
export function getProductById(id: number | string) {
  return unifiedProducts.find((p) => p.id === id);
}

// About section for Demo User
export const demoUserAbout = `Demo User là một người bán uy tín với nhiều năm kinh nghiệm trong lĩnh vực đấu giá trực tuyến. Chuyên cung cấp các sản phẩm điện tử chất lượng cao với giá cả hợp lý. Tất cả sản phẩm đều được kiểm tra kỹ lưỡng và bảo hành chính hãng. Demo User cam kết mang đến trải nghiệm mua sắm tốt nhất cho khách hàng.`;
